name: CI
on: [push]
jobs:
    linting:
        name: Lint code base
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Installing packages
              run: npm install

            - name: Running Eslint
              run: npm run lint
